# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ec6e026dfa3d417ae2547b08d453df0c497c2d945eb4dbf967c149f1534529b56101c93e08c8874ec3e969e37790c045834e719f1c906dc0af84f0c63bfce9c

test:
  secret_key_base: 4667a2b6f2835c2ab42588c0250d622a0d505b6426c87bc3ab7ed519514de1114e212acfe8803b7c2f6eeef270887022d2986c02bd583babde3dab86fae2c48d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
